DATA:
  PATH: /home/muthu/GitHub/MLOps/S3/dogsClassifier/ #/home/muthu/GitHub/DATA ğŸ“/
  folder_name: dogs_dataset
  num_workers: 0
  batch_size: 32

MODEL:
  name: resnet18
  pretrain: true
  num_class: 10
  lr: 0.04
  
Training:
  num_epochs: 15
  precision: 32
